### PR TITLE
fix(admin): remove NotFound component

### LINKED ISSUE #339: [BUG]: 'NotFound' (imported as 'NotFound') was not found in '@strapi/helper-plugin'
**Describe the bug**
I installed the latest version of this plugin on the current version of strapi and receive the following error when watching the admin:

```
WARNING in ../../node_modules/strapi-plugin-translate/admin/src/pages/App/index.js 7:276-284
export 'NotFound' (imported as 'NotFound') was not found in '@strapi/helper-plugin'

```

**To Reproduce**

1. Install Strapi
2. Install the plugin and add config
3. Run `strapi develop --watch-admin`

**Expected behavior**
Translation workflow et al seems to work despite the warning. However, I assume that some component will error out due to the missing dependency.

I assume this is a breaking change on the side of strapi.

**System (please complete the following information):**

- OS: macOS
- Browser [e.g. firefox, safari, chrome]
- Versions:
  - strapi: 4.14.4
  - strapi-plugin-translate: 1.2.2
  - provider:strapi-provider-translate-deepl@1.1.10

### PR DESCRIPTION
**Pull request by sargreal**
The NotFound component was removed in @strapi/helper-plugin and was not actually used

fix #339

### CODE REVIEW

File: plugin/admin/src/pages/App/index.js [hunk 1]
```diff
@@ -16,7 +15,6 @@ const App = () => {
     <div>
       <Switch>
         <Route path={`/plugins/${pluginId}`} component={HomePage} exact />
```
Comment (layaxx) [inline plugin/admin/src/pages/App/index.js:17]: Do we even need the whole Switch/Route thing at this point? I think just (re)exporting the Homepage component, maybe wrapped in a div, would work just as well?

Comment (sargreal) [reply plugin/admin/src/pages/App/index.js]: Your right, it's not necessary
