### PR TITLE
fix(batch-translate): catch errors from started jobs

### LINKED ISSUE #276: [BUG]: Server breaks when you Pause or Cancel bulk translate
**Describe the bug**
Server breaks after you Pause or Cancel any upgoing bulk translate collection. Need to restart the server again after that issue.

**To Reproduce**
1. Go to Translate plugin
2. Click on Start translate for any of the collection
3. Click on Pause/Cancel when process is ongoing.
4. Server breaks after that

**Expected behavior**
The server shouldn't break.

**Error Report**
``` 
0|app  | 2023-07-19T09:07:34: /node_modules/strapi-plugin-translate/plugin/server/services/batch-translate/BatchTranslateJob.js:253
0|app  | 2023-07-19T09:07:34:         throw new Error('Job was paused')
0|app  | 2023-07-19T09:07:34:               ^
0|app  | 2023-07-19T09:07:34: 
0|app  | 2023-07-19T09:07:34: Error: Job was paused
0|app  | 2023-07-19T09:07:34:     at BatchTranslateJob.start (/node_modules/strapi-plugin-translate/plugin/server/services/batch-translate/BatchTranslateJob.js:253:15)
0|app  | 2023-07-19T09:07:34:     at runMicrotasks (<anonymous>)
0|app  | 2023-07-19T09:07:34:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app  | 2023-07-19T09:07:34: Done in 143.77s.
```

**System (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Versions:
   - strapi: 4.9.0
   - strapi-plugin-translate: 1.1.6
   - provider: strapi-provider-translate-deepl@1.1.6
   
**Plugin config**
Please add your plugin config here, e.g.
```js
module.exports = {
  translate: {
    enabled: true,
    config: {
      provider: 'deepl',
      providerOptions: {
        apiKey: '*************'
      },
      translatedFieldTypes: [
        'string',
        { type: 'text', format: 'plain' },
        { type: 'richtext', format: 'markdown' },
        'component',
        'dynamiczone',
      ],
      translateRelations: true,
    },
  },
}
```

### PR DESCRIPTION
**Pull request by sargreal**
Fixes #276 

And some cosmetic changes

### CODE REVIEW

File: plugin/server/services/batch-translate/BatchTranslateManager.js [hunk 1]
```diff
@@ -35,11 +35,14 @@ class BatchTranslateManager {
       .create({ data: params })
     const job = new BatchTranslateJob(entity)
 
-    const promise = job.start()
+    const promise = job
```
Comment (layaxx) [inline plugin/server/services/batch-translate/BatchTranslateManager.js:38]: Fails ESlint check (variable assigned but not used)

**Review by layaxx — CHANGES_REQUESTED** [review]
Looks good apart from ESLint Error

**Review by layaxx — APPROVED** [review]
