### PR TITLE
fix: relations not translated in normal mode

### LINKED ISSUE #35: Strapi 4.5 support
When using this plugin in combination with strapi 4.5.x i cant use the translate form different locale feature in the content manager.
I traced the problem to the new way of (lazy) loading relations. This means that the data in the admin ui doesn't standard have the id's of the relations resulting in an error when trying to translate:

```
error: Translating entity failed: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [t0.id] query: where `t0`.`id` = ?
```

Are you going to offer strapi 4.5 support?

### PR DESCRIPTION
**Pull request by sargreal**
Due to changes in strapi 4.5, the relations are
- not loaded in the data sent to the server during translation
- changed differently on the frontend

This implementation fixes both issues by:
- submitting only the id for translation and loading the data on the server
- cleaning the translated data before passing it back to the client
- normalizing all relations before updating
- adding all fields with the onChange hook from the EditViewDataManager

fixes #35

### CODE REVIEW

File: admin/src/components/CMEditViewTranslateLocale/index.js [hunk 1]
```diff
@@ -131,41 +132,48 @@ const Content = ({
...
+        'updatedAt',
+      ].forEach((key) => {
+        _.omit(parsedData, key)
+
+        if (!initialData[key]) return
+        parsedData[key] = initialData[key]
       })
 
+      for (const key in parsedData) {
+        if (Object.hasOwnProperty.call(parsedData, key)) {
```
Comment (layaxx) [inline admin/src/components/CMEditViewTranslateLocale/index.js:167]: is there a reason for the .call instead of a regular call (i.e. `Object.hasOwnProperty(parsedData, key)`)?

File: admin/src/components/CMEditViewTranslateLocale/index.js [hunk 2]
```diff
@@ -131,41 +132,48 @@ const Content = ({
...
+      const parsedData = parseRelations(translatedData, allLayoutData)
 
-      // FIXME: Two issues here
-      // - Date/time field is only shown with value after save
-      // - The dispatch updates not just modified data but also the initial data
-      //   -> Saving is impossible until manual modification if object already existed
-      dispatch({
-        type: 'ContentManager/CrudReducer/GET_DATA_SUCCEEDED',
-        data: translatedData,
+      console.log(parsedData)
```
Comment (layaxx) [inline admin/src/components/CMEditViewTranslateLocale/index.js:151]:
```suggestion
```

File: admin/src/components/CMEditViewTranslateLocale/index.js (hunk 1 above)
Comment (sargreal) [reply admin/src/components/CMEditViewTranslateLocale/index.js:167]: That was the suggestion of a VSCode snippet.

Doing what you suggest creates an eslint error: `Do not access Object.prototype method 'hasOwnProperty' from target object eslint[no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins)`

Comment (layaxx) [reply admin/src/components/CMEditViewTranslateLocale/index.js:166]: Ok I understand. ´Object.hasOwnProperty(parsedData, key)´ would actually not have worked either way 😅

**Review by layaxx — APPROVED** [review]
